name: Test docs
on:
  pull_request:
    paths:
      - "docs/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        with:
          node-version: '16.15.1'

      - run: rm -rf build

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.5.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          projects: "@novu/docs"
          nxCloud: true
